services:
    Backend\Modules\GoogleReview\Command\UpdateScore:
        tags:
            - { name: 'console.command', command: 'google-review:update-score' }
        arguments:
            - "@logger"
            - "@fork.settings"
